### ISSUE TITLE
Boolean minifying

### ISSUE THREAD

**Issue by Ovsyanka** [tssajo/minjson#1]
Hello!
If i mimify json with boolean values they become not correct json statments:

``` js
echo {b: true} | minjson
//result: {"b":!0}
echo {b: false} | minjson
//result: {"b":!1}
```

**Comment by tssajo** [comment]
You are right and thanks for the report!

Unfortunately, I have no idea how to fix this... :(

Here is the thing: If you look at how minjson works (see this file: https://github.com/tssajo/minjson/blob/master/jsonminifier.js ) then you'll see that it is using UglifyJS ( https://github.com/mishoo/UglifyJS2 ) to do the actual minification.

UglifyJS was created for Javascript minification, not for JSON minification.

I only created this small minjson package as an external CLI tool for my SublimeText Minify package ( https://github.com/tssajo/Minify ) because somebody requested the JSON minification feature, please see: https://github.com/tssajo/Minify/issues/26
So I did the implementation exactly as it was suggested to me in that feature request by @victorleblais

If you can think of an easy way to fix this problem with the boolean values then please submit a PR and I will merge that in.

Thanks!

**Comment by Ovsyanka** [comment]
Thank you for detailed answer.

I suggest you a couple solutions in my pull-request. Please see it.

And i think you should make some unit-tests in future time, because it will be really helpful to such refactoring.

**Comment by tssajo** [comment]
I merged your pull request. Thank you! I will bump the version number in a few minutes.

Regarding unit tests, I agree with you. However, please keep in mind that this little program is just an extremely simple CLI tool with only a few lines of program code. The main processing is being done by UglifyJS an external dependency,, not by this program. In addition to this, I rarely (almost never) use this program. I only created it because of the feature request ( https://github.com/tssajo/Minify/issues/26 ) I mentioned to you earlier. ;)

If you want to add tests then please go ahead and I will merge in everything you submit as a PR.

Thanks, again!

**Comment by tssajo** [comment]
FYI: I bumped the version number to 0.0.2
